/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

/**
 *
 * @author Lenovo
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
    initComponents();
    setLocationRelativeTo(null);
    setResizable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnReservasi = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnTamu = new javax.swing.JButton();
        btnKamar = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        lblStatistik = new javax.swing.JLabel();
        lblTextJumlahKamar = new javax.swing.JLabel();
        lblTextKamarKosong = new javax.swing.JLabel();
        lblTextReservasiAktif = new javax.swing.JLabel();
        lblTextPendapatan = new javax.swing.JLabel();
        lblJumlahKamar = new javax.swing.JLabel();
        lblKamarKosong = new javax.swing.JLabel();
        lblReservasiAktif = new javax.swing.JLabel();
        lblPendapatan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard - Sistem Reservasi Hotel");
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setText("SISTEM RESERVASI HOTEL");

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblWelcome.setText("Selamat Datang Admin");

        btnReservasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReservasi.setText("Reservasi");
        btnReservasi.setPreferredSize(new java.awt.Dimension(170, 60));
        btnReservasi.addActionListener(this::btnReservasiActionPerformed);

        btnPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPembayaran.setText("Pembayaran");
        btnPembayaran.setPreferredSize(new java.awt.Dimension(170, 60));
        btnPembayaran.addActionListener(this::btnPembayaranActionPerformed);

        btnTamu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTamu.setText("Data Tamu");
        btnTamu.setPreferredSize(new java.awt.Dimension(170, 60));
        btnTamu.addActionListener(this::btnTamuActionPerformed);

        btnKamar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKamar.setText("Data Kamar");
        btnKamar.setPreferredSize(new java.awt.Dimension(170, 60));
        btnKamar.addActionListener(this::btnKamarActionPerformed);

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setPreferredSize(new java.awt.Dimension(170, 60));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnLaporan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setPreferredSize(new java.awt.Dimension(170, 60));
        btnLaporan.addActionListener(this::btnLaporanActionPerformed);

        lblStatistik.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatistik.setText("Statistik Hotel");

        lblTextJumlahKamar.setText("Jumlah Kamar :");

        lblTextKamarKosong.setText("Kamar Kosong :");

        lblTextReservasiAktif.setText("Reservasi Aktif :");

        lblTextPendapatan.setText("Pendapatan :");

        lblJumlahKamar.setText("5");

        lblKamarKosong.setText("5");

        lblReservasiAktif.setText("0");

        lblPendapatan.setText("Rp 100.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(lblJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblWelcome)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(btnTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatistik)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblTextReservasiAktif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTextKamarKosong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTextJumlahKamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblTextPendapatan))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblJumlahKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblKamarKosong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReservasiAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblStatistik)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextJumlahKamar)
                    .addComponent(lblJumlahKamar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextKamarKosong)
                    .addComponent(lblKamarKosong))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextReservasiAktif)
                    .addComponent(lblReservasiAktif))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextPendapatan)
                    .addComponent(lblPendapatan))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
ReservasiForm reservasi = new ReservasiForm();
    reservasi.setLocationRelativeTo(null);
    reservasi.setVisible(true);

    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservasiActionPerformed

    private void btnTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamuActionPerformed
TamuForm tamu = new TamuForm();
    tamu.setLocationRelativeTo(null);
    tamu.setVisible(true);

    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnTamuActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
new Pembayaran().setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarActionPerformed
new KamarForm().setVisible(true);
this.dispose();

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKamarActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
new LoginForm().setVisible(true);
this.dispose();

this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
new LaporanForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKamar;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JButton btnTamu;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlahKamar;
    private javax.swing.JLabel lblKamarKosong;
    private javax.swing.JLabel lblPendapatan;
    private javax.swing.JLabel lblReservasiAktif;
    private javax.swing.JLabel lblStatistik;
    private javax.swing.JLabel lblTextJumlahKamar;
    private javax.swing.JLabel lblTextKamarKosong;
    private javax.swing.JLabel lblTextPendapatan;
    private javax.swing.JLabel lblTextReservasiAktif;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
