/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class KamarForm extends javax.swing.JFrame {
    private String idKamar;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KamarForm.class.getName());

    /**
     * Creates new form KamarForm
     */
   public KamarForm() {
    initComponents();
    setLocationRelativeTo(null);
    setResizable(false);

    tblKamar.setRowHeight(25);

   tampilData();
   resetForm();
}

   private void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nomor Kamar");
    model.addColumn("Tipe");
    model.addColumn("Harga");
    model.addColumn("Status");

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT * FROM kamar";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_kamar"),
                rs.getString("nomor_kamar"),
                rs.getString("tipe"),
                rs.getString("harga"),
                rs.getString("status")
            });

        }

        tblKamar.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e.getMessage());

    }

}
    private void resetForm() {

    txtNomor.setText("");
    cmbTipe.setSelectedIndex(0);
    txtHarga.setText("");
    cmbStatus.setSelectedIndex(0);

    txtNomor.requestFocus();

}

private void cariData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nomor Kamar");
    model.addColumn("Tipe");
    model.addColumn("Harga");
    model.addColumn("Status");

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT * FROM kamar WHERE nomor_kamar LIKE ? OR tipe LIKE ?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, "%" + txtCari.getText() + "%");
        pst.setString(2, "%" + txtCari.getText() + "%");

        ResultSet rs = pst.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{
                rs.getString("id_kamar"),
                rs.getString("nomor_kamar"),
                rs.getString("tipe"),
                rs.getString("harga"),
                rs.getString("status")
            });

        }

        tblKamar.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
/**
 This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblJudul = new javax.swing.JLabel();
        lblNomor = new javax.swing.JLabel();
        lblTipe = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtNomor = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        cmbTipe = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblCari = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKamar = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudul.setText("DATA KAMAR");

        lblNomor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomor.setText("Nomor Kamar      :");

        lblTipe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipe.setText("Tipe Kamar           :");

        lblHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHarga.setText("Harga                   :");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatus.setText("Status                   :");

        txtNomor.addActionListener(this::txtNomorActionPerformed);

        cmbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Deluxe", "Suite" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kosong", "Terisi" }));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        lblCari.setText("Cari :");

        tblKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKamarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKamar);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(lblJudul)
                .addContainerGap(332, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCari)
                                .addGap(18, 18, 18)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTambah)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNomor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNomor)
                                            .addComponent(txtHarga)
                                            .addComponent(cmbTipe, 0, 254, Short.MAX_VALUE)
                                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(btnUbah)
                                        .addGap(41, 41, 41)
                                        .addComponent(btnHapus)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnReset)))))
                        .addGap(42, 42, 42)
                        .addComponent(btnKembali)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblJudul)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomor)
                    .addComponent(txtNomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipe)
                    .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomorActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "INSERT INTO kamar(nomor_kamar, tipe, harga, status) VALUES (?,?,?,?)";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, txtNomor.getText());
    pst.setString(2, cmbTipe.getSelectedItem().toString());
    pst.setString(3, txtHarga.getText());
    pst.setString(4, cmbStatus.getSelectedItem().toString());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan");

    tampilData();
    resetForm();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}      // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "UPDATE kamar SET nomor_kamar=?, tipe=?, harga=?, status=? WHERE id_kamar=?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, txtNomor.getText());
    pst.setString(2, cmbTipe.getSelectedItem().toString());
    pst.setString(3, txtHarga.getText());
    pst.setString(4, cmbStatus.getSelectedItem().toString());
    pst.setString(5, idKamar);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Data berhasil diubah");

    tampilData();
    resetForm();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKamarMouseClicked
int baris = tblKamar.getSelectedRow();

idKamar = tblKamar.getValueAt(baris, 0).toString();

txtNomor.setText(tblKamar.getValueAt(baris, 1).toString());
cmbTipe.setSelectedItem(tblKamar.getValueAt(baris, 2).toString());
txtHarga.setText(tblKamar.getValueAt(baris, 3).toString());
cmbStatus.setSelectedItem(tblKamar.getValueAt(baris, 4).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tblKamarMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "DELETE FROM kamar WHERE id_kamar=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, idKamar);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

        tampilData();
        resetForm();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
cariData();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
new DashboardForm().setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KamarForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTipe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNomor;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipe;
    private javax.swing.JTable tblKamar;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNomor;
    // End of variables declaration//GEN-END:variables
}
