/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import java.util.Date;
import java.text.SimpleDateFormat;
/**
 *
 * @author Lenovo
 */
public class Pembayaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pembayaran.class.getName());

    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
    initComponents();

    tampilData();
    loadReservasi();
    resetForm();
}

    private void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("ID Reservasi");
    model.addColumn("Tanggal Bayar");
    model.addColumn("Metode");
    model.addColumn("Jumlah");
    model.addColumn("Status");

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT p.*, t.nama, k.nomor_kamar "
           + "FROM pembayaran p "
           + "JOIN reservasi r ON p.id_reservasi = r.id_reservasi "
           + "JOIN tamu t ON r.id_tamu = t.id_tamu "
           + "JOIN kamar k ON r.id_kamar = k.id_kamar";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
    rs.getString("id_pembayaran"),
    rs.getString("id_reservasi") + " - " + rs.getString("nama") + " - " + rs.getString("nomor_kamar"),
    rs.getString("tanggal_bayar"),
    rs.getString("metode"),
    rs.getString("jumlah"),
    rs.getString("status")
});

        }

        tblPembayaran.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
    private void loadReservasi() {

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT id_reservasi FROM reservasi";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        cmbReservasi.removeAllItems();

        while (rs.next()) {

            cmbReservasi.addItem(rs.getString("id_reservasi"));

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
    private String idPembayaran = "";

private void resetForm() {

    cmbReservasi.setSelectedIndex(0);
    dcTanggalBayar.setDate(null);
    cmbMetode.setSelectedIndex(0);
    txtJumlah.setText("");
    cmbStatus.setSelectedIndex(0);

    idPembayaran = "";

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbReservasi = new javax.swing.JComboBox<>();
        dcTanggalBayar = new com.toedter.calendar.JDateChooser();
        cmbMetode = new javax.swing.JComboBox<>();
        txtJumlah = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembayaran = new javax.swing.JTable();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Pembayaran");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID Reservasi :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Bayar :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Metode Pembayaran :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Status :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah :");

        cmbReservasi.addItemListener(this::cmbReservasiItemStateChanged);

        cmbMetode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Transfer", "QRIS" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Cari :");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tblPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembayaran);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbReservasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcTanggalBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbMetode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJumlah)
                                    .addComponent(cmbStatus, 0, 355, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnTambah)
                        .addGap(27, 27, 27)
                        .addComponent(btnUbah)
                        .addGap(33, 33, 33)
                        .addComponent(btnHapus)
                        .addGap(29, 29, 29)
                        .addComponent(btnReset)
                        .addGap(34, 34, 34)
                        .addComponent(btnKembali)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(dcTanggalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
try {

    Connection conn = Koneksi.getKoneksi();

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    String tanggalBayar = sdf.format(dcTanggalBayar.getDate());

    String sql = "INSERT INTO pembayaran(id_reservasi, tanggal_bayar, metode, jumlah, status) VALUES(?,?,?,?,?)";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, cmbReservasi.getSelectedItem().toString());
pst.setString(2, tanggalBayar);
pst.setString(3, cmbMetode.getSelectedItem().toString());
pst.setDouble(4, Double.parseDouble(txtJumlah.getText()));
pst.setString(5, cmbStatus.getSelectedItem().toString());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Data pembayaran berhasil ditambahkan");

    tampilData();
    resetForm();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}       // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void cmbReservasiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbReservasiItemStateChanged
try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "SELECT total_bayar FROM reservasi WHERE id_reservasi=?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, cmbReservasi.getSelectedItem().toString());

    ResultSet rs = pst.executeQuery();

    if (rs.next()) {

        txtJumlah.setText(rs.getString("total_bayar"));

    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_cmbReservasiItemStateChanged

    private void tblPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembayaranMouseClicked
 int baris = tblPembayaran.getSelectedRow();

    idPembayaran = tblPembayaran.getValueAt(baris, 0).toString();

    cmbReservasi.setSelectedItem(tblPembayaran.getValueAt(baris, 1).toString());

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        dcTanggalBayar.setDate(sdf.parse(tblPembayaran.getValueAt(baris, 2).toString()));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    cmbMetode.setSelectedItem(tblPembayaran.getValueAt(baris, 3).toString());

    txtJumlah.setText(tblPembayaran.getValueAt(baris, 4).toString());

    cmbStatus.setSelectedItem(tblPembayaran.getValueAt(baris, 5).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPembayaranMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
try {

    Connection conn = Koneksi.getKoneksi();

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String tanggalBayar = sdf.format(dcTanggalBayar.getDate());

    String sql = "UPDATE pembayaran SET id_reservasi=?, tanggal_bayar=?, metode=?, jumlah=?, status=? WHERE id_pembayaran=?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, cmbReservasi.getSelectedItem().toString());
    pst.setString(2, tanggalBayar);
    pst.setString(3, cmbMetode.getSelectedItem().toString());
    pst.setDouble(4, Double.parseDouble(txtJumlah.getText()));
    pst.setString(5, cmbStatus.getSelectedItem().toString());
    pst.setString(6, idPembayaran);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Data pembayaran berhasil diubah");

    tampilData();
    resetForm();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "DELETE FROM pembayaran WHERE id_pembayaran=?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, idPembayaran);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this, "Data pembayaran berhasil dihapus");

    tampilData();
    resetForm();

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
resetForm();        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("ID Reservasi");
    model.addColumn("Tanggal Bayar");
    model.addColumn("Metode");
    model.addColumn("Jumlah");
    model.addColumn("Status");

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT * FROM pembayaran WHERE id_reservasi LIKE ?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, "%" + txtCari.getText() + "%");

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getString("id_pembayaran"),
                rs.getString("id_reservasi"),
                rs.getString("tanggal_bayar"),
                rs.getString("metode"),
                rs.getString("jumlah"),
                rs.getString("status")
            });

        }

        tblPembayaran.setModel(model);
        tblPembayaran.getColumnModel().getColumn(0).setPreferredWidth(40);   // ID
tblPembayaran.getColumnModel().getColumn(1).setPreferredWidth(70);   // ID Reservasi
tblPembayaran.getColumnModel().getColumn(2).setPreferredWidth(100);  // Tanggal
tblPembayaran.getColumnModel().getColumn(3).setPreferredWidth(100);  // Metode
tblPembayaran.getColumnModel().getColumn(4).setPreferredWidth(130);  // Jumlah
tblPembayaran.getColumnModel().getColumn(5).setPreferredWidth(80);   // Status

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
new DashboardForm().setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pembayaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbMetode;
    private javax.swing.JComboBox<String> cmbReservasi;
    private javax.swing.JComboBox<String> cmbStatus;
    private com.toedter.calendar.JDateChooser dcTanggalBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPembayaran;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
